version: "3"
services:
  app:
    build:
      dockerfile: "Dockerfile"
      context: .
    ports:
      - "8080"
  postgres:
    image: "postgres:15.2"
    ports:
      - "5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=var/lib/postgres/data/pgdata




