version: "3"
services:
  app:
    build:
      dockerfile: "Dockerfile"
      context: .
    ports:
      - "8080"
  postgres:
    image: "postgres:15.2"
    ports:
      - "5432"
    environment:
      - POSTGRES_USER="adrem"
      - POSTGRES_PASSWORD="149414"
      - PGDATA=/var/lib/postgres/data/pgdata




